server:
  port: 8082

spring:
  profiles:
    active: dev
  graphql:
    schema:
      locations: classpath:graphql
  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/${DB_NAME}?createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    properties:
      format_sql: false
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        ddl-auto: none
        globally_quoted_identifiers: true

